<a href="https://colab.research.google.com/github/DevKumar57-67/PROJECT-FIESTA-AI/blob/main/Simulogy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

            SIMULOGY

Simulogy stands for
Simulation Technology which is the engineering of building simulations baeed on calculations and create effective software systems which can be used to solve complex engineering problems.

           Overview

The subject involves Physics, Mathematics, Computer Science and Multiple Enginnering branches to solve problems in specific fields.

In [10]:
# Numpy Tutorials
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
arr2= np.array([6,7,8,9,10])
print(arr2)
arr = arr1+arr2
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [11]:
# Use of numpy in basic problem

pos = np.array([100,200,300])
print(pos)

'''
This means:

x = 100
y = 200
z = 300

In real-world terms, imagine:

100 km east
200 km north
500 km altitude

This is exactly how real simulation systems track position.

'''

[100 200 300]


'\nThis means:\n\nx = 100\ny = 200\nz = 300\n\nIn real-world terms, imagine:\n\n100 km east\n200 km north\n500 km altitude\n\nThis is exactly how real simulation systems track position.\n\n'