<a href="https://colab.research.google.com/github/DevKumar57-67/PROJECT-FIESTA-AI/blob/main/Simulogy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
# SIMULOGY
```




Simulogy stands for
Simulation Technology which is the engineering of building simulations baeed on calculations and create effective software systems which can be used to solve complex engineering problems.

           Overview

The subject involves Physics, Mathematics, Computer Science and Multiple Enginnering branches to solve problems in specific fields.

In [ ]:
# Numpy Tutorials
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
arr2= np.array([6,7,8,9,10])
print(arr2)
arr = arr1+arr2
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [ ]:
# Use of numpy in basic problem

pos = np.array([100,200,300])
print(pos)

'''
This means:

x = 100
y = 200
z = 300

In real-world terms, imagine:

100 km east
200 km north
500 km altitude

This is exactly how real simulation systems track position.

'''

[100 200 300]


'\nThis means:\n\nx = 100\ny = 200\nz = 300\n\nIn real-world terms, imagine:\n\n100 km east\n200 km north\n500 km altitude\n\nThis is exactly how real simulation systems track position.\n\n'

In [1]:
import numpy as np

def simulate_universe_age(H0, omega_m, omega_lambda, da=0.0001):
    """
    Simulates the age of the universe using numerical integration.

    Parameters:
        H0 (float): Hubble constant in km/s/Mpc
        omega_m (float): Matter density parameter
        omega_lambda (float): Dark energy density parameter
        da (float): Step size for numerical integration

    Returns:
        float: Age of the universe in billion years
    """

    # Convert H0 to SI unit (s^-1)
    MPC_IN_KM = 3.086e19
    H0_si = H0 / MPC_IN_KM

    # Start simulation
    a = 0.0001
    age_seconds = 0

    while a <= 1.0:
        H_a = H0_si * np.sqrt((omega_m / a**3) + omega_lambda)
        dt = da / (a * H_a)
        age_seconds += dt
        a += da

    # Convert seconds to billion years
    SECONDS_IN_YEAR = 3.154e7
    age_years = age_seconds / SECONDS_IN_YEAR
    age_billion_years = age_years / 1e9

    return age_billion_years


# -------- User Input Section --------
print("=== Universe Age Simulation System ===")

H0 = float(input("Enter Hubble constant H0 (km/s/Mpc): "))
omega_m = float(input("Enter matter density Ωm: "))
omega_lambda = float(input("Enter dark energy density ΩΛ: "))

age = simulate_universe_age(H0, omega_m, omega_lambda)

print(f"\nEstimated age of the universe: {age:.2f} billion years")

=== Universe Age Simulation System ===
Enter Hubble constant H0 (km/s/Mpc): 70
Enter matter density Ωm: 0.6
Enter dark energy density ΩΛ: 0.5

Estimated age of the universe: 10.79 billion years


In [2]:
import numpy as np

def simulate_universe_age(H0, omega_m, omega_lambda, da=0.0001):
    """
    Simulates the age of the universe using numerical integration.
    Returns age in billion years.
    """

    # Convert H0 from km/s/Mpc to s^-1
    MPC_IN_KM = 3.086e19
    H0_si = H0 / MPC_IN_KM

    a = 0.0001
    age_seconds = 0

    while a <= 1.0:
        expansion_term = (omega_m / a**3) + omega_lambda

        if expansion_term <= 0:
            raise ValueError("Invalid cosmological parameters: expansion term became non-positive.")

        H_a = H0_si * np.sqrt(expansion_term)
        dt = da / (a * H_a)

        age_seconds += dt
        a += da

    # Convert to billion years
    SECONDS_IN_YEAR = 3.154e7
    age_billion_years = age_seconds / SECONDS_IN_YEAR / 1e9

    return age_billion_years


def validate_inputs(H0, omega_m, omega_lambda):
    """
    Validates user input values.
    """
    if H0 <= 0:
        raise ValueError("Hubble constant must be positive.")

    if omega_m < 0 or omega_lambda < 0:
        raise ValueError("Density parameters cannot be negative.")

    total_density = omega_m + omega_lambda

    if total_density <= 0:
        raise ValueError("Total density must be greater than zero.")

    return True


def sensitivity_analysis(H0, omega_m, omega_lambda):
    """
    Shows how age changes with ±5% H0 variation.
    """
    base_age = simulate_universe_age(H0, omega_m, omega_lambda)

    lower_age = simulate_universe_age(H0 * 0.95, omega_m, omega_lambda)
    upper_age = simulate_universe_age(H0 * 1.05, omega_m, omega_lambda)

    print("\n=== Sensitivity Analysis (±5% H0) ===")
    print(f"H0 = {H0*0.95:.2f} -> Age = {lower_age:.2f} billion years")
    print(f"H0 = {H0:.2f} -> Age = {base_age:.2f} billion years")
    print(f"H0 = {H0*1.05:.2f} -> Age = {upper_age:.2f} billion years")


# -------- Main Program --------
print("=== Universe Age Simulation System v2 ===")

try:
    H0 = float(input("Enter Hubble constant H0 (km/s/Mpc): "))
    omega_m = float(input("Enter matter density Ωm: "))
    omega_lambda = float(input("Enter dark energy density ΩΛ: "))

    validate_inputs(H0, omega_m, omega_lambda)

    age = simulate_universe_age(H0, omega_m, omega_lambda)

    print(f"\nEstimated age of the universe: {age:.2f} billion years")

    sensitivity_analysis(H0, omega_m, omega_lambda)

except ValueError as e:
    print(f"\nInput Error: {e}")

=== Universe Age Simulation System v2 ===
Enter Hubble constant H0 (km/s/Mpc): -78
Enter matter density Ωm: 4
Enter dark energy density ΩΛ: 7

Input Error: Hubble constant must be positive.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def simulate_universe_age(H0, omega_m, omega_lambda, da=0.0001):
    """
    Simulates the age of the universe using numerical integration.
    Returns age in billion years.
    """

    MPC_IN_KM = 3.086e19
    H0_si = H0 / MPC_IN_KM

    a = 0.0001
    age_seconds = 0

    while a <= 1.0:
        expansion_term = (omega_m / a**3) + omega_lambda

        if expansion_term <= 0:
            raise ValueError("Invalid cosmological parameters.")

        H_a = H0_si * np.sqrt(expansion_term)
        dt = da / (a * H_a)

        age_seconds += dt
        a += da

    SECONDS_IN_YEAR = 3.154e7
    age_billion_years = age_seconds / SECONDS_IN_YEAR / 1e9

    return age_billion_years


def validate_inputs(H0, omega_m, omega_lambda):
    if H0 <= 0:
        raise ValueError("Hubble constant must be positive.")

    if omega_m < 0 or omega_lambda < 0:
        raise ValueError("Density parameters cannot be negative.")


def plot_age_vs_hubble(omega_m, omega_lambda):
    """
    Plots universe age vs Hubble constant.
    """
    H0_values = np.linspace(60, 80, 50)
    age_values = []

    for H0 in H0_values:
        age = simulate_universe_age(H0, omega_m, omega_lambda)
        age_values.append(age)

    plt.figure(figsize=(8, 5))
    plt.plot(H0_values, age_values)
    plt.xlabel("Hubble Constant H0 (km/s/Mpc)")
    plt.ylabel("Age of Universe (billion years)")
    plt.title("Universe Age vs Hubble Constant")
    plt.grid(True)
    plt.show()


# -------- Main Program --------
print("=== Universe Age Simulation System v3 ===")

try:
    H0 = float(input("Enter Hubble constant H0 (km/s/Mpc): "))
    omega_m = float(input("Enter matter density Ωm: "))
    omega_lambda = float(input("Enter dark energy density ΩΛ: "))

    validate_inputs(H0, omega_m, omega_lambda)

    age = simulate_universe_age(H0, omega_m, omega_lambda)

    print(f"\nEstimated age of the universe: {age:.2f} billion years")

    plot_age_vs_hubble(omega_m, omega_lambda)

except ValueError as e:
    print(f"\nInput Error: {e}")

=== Universe Age Simulation System v3 ===
