<a href="https://colab.research.google.com/github/DevKumar57-67/PROJECT-FIESTA-AI/blob/main/Simulogy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

            SIMULOGY

Simulogy stands for
Simulation Technology which is the engineering of building simulations baeed on calculations and create effective software systems which can be used to solve complex engineering problems.

           Overview

The subject involves Physics, Mathematics, Computer Science and Multiple Enginnering branches to solve problems in specific fields.

In [2]:
# Numpy Tutorials
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
arr2= np.array([6,7,8,9,10])
print(arr2)
arr = arr1+arr2
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [3]:
for i in range(0,5):
    print("*")

*
*
*
*
*
